#! /bin/sh

#Primer mod segun github Atareao
pkill sxhkd
sxhkd &

	# inicia polybar con colorblocks
	"${HOME}/.config/polybar/colorblocks/launch.sh"
	#fondo de pantalla
feh --bg-fill /home/gmb/Pictures/wallpaper.jpg
feh --bg-fill /home/gmb/Pictures/wallpaper.jpg &


#Fin de la primer mod

#prueba1

xrandr --output DVI-1 --primary --mode 1920x1080

#test para ordenar monitores
bspc wm --reoder-monitors DVI-1 HDMI-0

bspc monitor DVI-1 -d 1 2 3 4 5 6 


#bspc monitor HDMI-0 -n monitor secundario -d 9
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          0
bspc config bottom_padding        0
bspc config left_padding          0
bspc config right_padding         0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Comienzo 2da mod segun atareao
bspc config pointer_follows_focus true

bspc config automatic_scheme  	  alternate
bspc config removal_adjustment
bspc config honor_size_hints
bspc config ignore_ewmh_struts

bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true

# For Pycharm and Intellj
wmname LG3D

#BSPWM coloring
bspc config normal_border_color		"#1f1f1f"
bspc config active_border_color		"#1f1f1f"
bspc config focused_border_color	"#ffb300"
bspc config presel_feedback_color	"#5e81ac"

#bspc config urgent_border_color 	"#dd2727"

#Fin 2da mod segun atareao

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#pruebas
bspc rule -a google-chrome='^2'
bspc rule -a brave-browser='^2'


#autostars..
picom &
# $HOME/.config/polybarDefault/launch.sh &
$HOME/.config/polybar/launch.sh --blocks

